authentication/urls.py
from django.urls import path
from . import views

app_name="auth"

urlpatterns = [
    path('', views.login, name='home'),
    path('SignUp/', views.signup_user, name='signup'),
    path('Login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout')
]

betking_master/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls', namespace='auth')),
    path('', include('dashboard.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name='home'),
]

authentication/models.py
from django.db import models
# from django.contrib.auth.models import AbstractUser

# # Create your models here.

# class User(AbstractUser):
#     is_agent = models.BooleanField(default=True)
    
#     def __str__(self):
#         return self.username

dashboard/models.py
from django.db import models

# Create your models here.

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class SignUpForm(UserCreationForm):
    # Add any additional fields you want for registration
    email = forms.EmailField(required=True)
    phone_number = forms.CharField()
    
    class Meta:
        model = User
        fields = ['username', 'last_name', 'email', 'phone_number', 'password1', 'password2']

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
        
        

authentication/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm



def signup_user(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, 'Your account has been created successful, please login to continue')
            return redirect('auth:login')
        else:
            messages.warning(request, 'Something went wrong check you inputs')
            return redirect('auth:signup')
    else:
        form = SignUpForm()
    return render(request, 'authentication/signup.html', {'form': form})

def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
            messages.info(request, 'Login successfull enjoy session')
            return redirect('home')
        else:
            messages.warning(request, 'Something went wrong check you inputs')
            
    else:
        return render(request, 'authentication/login.html')


def logout_user(request):
    logout(request)
    messages.info(request, 'Your session has expired, login to continue')
    return redirect('auth:login')

        

# class SignUpView(CreateView):
#     template_name = 'signup.html'
#     form_class = SignUpForm
#     success_url = '/login/'

#     def form_valid(self, form):
#         response = super().form_valid(form)
#         messages.success(self.request, 'Account created successfully. You can now log in.')
#         return response

# class CustomLoginView(LoginView):
#     template_name = 'login.html'
#     authentication_form = AuthenticationForm

#     def form_valid(self, form):
#         response = super().form_valid(form)
#         messages.success(self.request, 'Logged in successfully.')
#         return response

# class CustomLogoutView(LogoutView):
#     next_page = '/login/'

#     def get(self, request, *args, **kwargs):
#         messages.success(self.request, 'Logged out successfully.')
#         return super().get(request, *args, **kwargs)

# class CustomPasswordResetView(PasswordResetView):
#     template_name = 'password_reset.html'
#     form_class = CustomPasswordResetForm
#     success_url = '/password-reset/done/'

#     def form_valid(self, form):
#         response = super().form_valid(form)
#         messages.success(self.request, 'Password reset email sent successfully.')
#         return response

# class CustomPasswordResetConfirmView(PasswordResetConfirmView):
#     template_name = 'password_reset_confirm.html'
#     success_url = '/password-reset/complete/'

#     def form_valid(self, form):
#         response = super().form_valid(form)
#         messages.success(self.request, 'Password reset successful. You can now log in with your new password.')
#         return response

dashboard/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request,'dashboard/home.html')

templates/authentication/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <link href="https://api.fontshare.com/v2/css?f[]=montserrat@500,900,700,200,401,301,400,100,101,201,800,300,600,501&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<>

    <!-- screen blur divisions -->

    <div class="blur"></div>
    <div class="blur2"></div>

    <!-- Navigation Bar section  -->

    {% block content %}
    {% endblock %}    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
</body>
</html>

templates/authentication/login.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %} SignUp Page {% endblock %}

{% block content %}
<style>
    .alert{
        position: fixed;
        margin-top: 3rem;
        width: 80%;
        top: 0;
        left: 0;
        right: 0;
        text-align: center;
        span{
            color: #000;
            font-size: 15px;
        }
    }
</style>

 <!-- Navigation Bar section  -->
    <section class="auth">

        {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-{{ msg.tags }} mx-auto"  alert-dismissible fade show" role="alert">
        <span>{{ msg }}</span>
        </div>
        {% endfor %}
        {% endif %}
   
        <div class="wrapper">
            <form action="" method="POST">
                {% csrf_token %}
                <h1>Registration</h1>
                <div class="input-box">
                    <div class="input-field">
                        <input type="text" name="username"  placeholder="Enter Username">
                        <i class='bx bxs-envelope' ></i>
                    </div>
                    <div class="input-field">
                        <input type="password" name="password" placeholder="Enter Password">
                        <i class='bx bxs-user'></i>
                    </div>
                </div>
                
                <label for=""><input type="checkbox">I hereby declare that the above information provided is true and correct</label>
                <p>Don't have an account create one <a href="{% url 'auth:signup' %}">here</a></p>
                <button class="btn" type="submit">Login</button>
            </form>
        </div>

    </section>

{% endblock %}

templates/authentication/signup.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block title %} SignUp Page {% endblock %}

{% block content %}

<style>
    .alert{
        position: fixed;
        margin-top: 3rem;
        width: 80%;
        top: 0;
        left: 0;
        right: 0;
        text-align: center;
        span{
            color: #000;
        }
    }
</style>

 <!-- Navigation Bar section  -->
    <section class="auth">
        {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-{{ msg.tags }} mx-auto" alert-dismissible fade show" role="alert">
        <span>{{ msg }}</span>
        </div>
        {% endfor %}
        {% endif %}
   
        <div class="wrapper">
            <form action="" method="POST">
                {% csrf_token %}
                <h1>Registration</h1>
                <div class="input-box">
                    <div class="input-field">
                        <input type="text" name="username"  placeholder="First Name" >
                        <i class='bx bxs-user'></i>
                    </div>
                    <div class="input-field">
                        <input type="text" name="last_name" placeholder="Last Name" >
                        <i class='bx bxs-user'></i>
                    </div>
                </div>
                <div class="input-box">
                    <div class="input-field">
                        <input type="email" name="email" placeholder="Email" >
                        <i class='bx bxs-envelope' ></i>
                    </div>
                    <div class="input-field">
                        <input type="number" name="phone_number" placeholder="Phone Number">
                        <i class='bx bxs-phone'></i>
                    </div>
                </div>
                <div class="input-box">
                    <div class="input-field">
                        <input type="password" name="password1" placeholder="Password">
                        <i class='bx bxs-lock-alt'></i>
                    </div>
                    <div class="input-field">
                        <input type="password" name="password2" placeholder="Confirm password">
                        <i class='bx bxs-lock-alt'></i>
                    </div>
                </div>
                <label for=""><input type="checkbox">I hereby declare that the above information provided is true and correct</label>
                <p>Already have an account login <a href="{% url 'auth:login' %}">here</a></p>
                <button class="btn" type="submit">Register</button>
            </form>
        </div>

    </section>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
    <link href="https://api.fontshare.com/v2/css?f[]=montserrat@500,900,700,200,401,301,400,100,101,201,800,300,600,501&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <!-- screen blur divisions -->

    <div class="blur"></div>
    <div class="blur2"></div>

    <!-- Navigation Bar section  -->

    <nav class="nav">
        <div class="nav-left">
            <img src="{% static 'images/Logo.png' %}" alt="">
        </div>
        <div class="nav-center">
            <ul>
                <li><a href="index.html" class="active">Home</a></li>
                <li><a href="admin.html">Admin</a></li>
                <li><a href="agent_list.html">Agents</a></li>
                <li><a href="contact.html">Contact</a></li>
                <li><a href="shops.html">Shop</a></li>
                <li><a href="faqs.html">FAGS</a></li>
            </ul>
        </div>
        <div class="nav-right">
            <a href="{% url 'auth:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a>
            <a href="{% url 'auth:signup' %}"><i class="fa fa-user" aria-hidden="true"></i>SignUp</a>
            <i class="fa fa-bars" onclick=OpenSidebar() id="onSideBar" aria-hidden="true"></i>
        </div>
    </nav>

            <!-- sidebar section -->

    <nav class="sidebar">
        <ul>
            <li><a class="close" onclick=CloseSideBar() href=""><i class="fa fa-times" aria-hidden="true"></i></a></li>   
                <li><a href="index.html">Home</a></li>
                <li><a href="admin.html">Admin</a></li>
                <li><a href="agent_list.html">Agent List</a></li>
                <li><a href="contact.html">Contact</a></li>
                <li><a href="shops.html">Shop</a></li>
                <li><a href="faqs.html">FAGS</a></li>
            </ul>
        </div>
    </nav>

    {% block content %}

    {% endblock %}
        <!-- footer betking section -->

        <section class="footer">
            <div class="footer__head">
                <div class="head__left">
                    <img src="{% static 'images/Logo.svg' %}" alt="logo">
                    <br>
                    <br>
                    <p>
                        You Most be atleast a 18yrs Old to Use our site.
                        Don’t try it if you not a football fan we’hv got 
                        get testimonies from our customer who are 
                        using this plat form the right way 
                    </p>
                </div>
                <div class="head__right">
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="admin.html">Admin</a></li>
                        <li><a href="agent_list.html">Agent List</a></li>
                        <li><a href="#">Contact</a></li>
                        <li><a href="shops.html">Shop</a></li>
                        <li><a href="#">FAGS</a></li>
                        <li><a href="#">logout</a></li>
                        <li><a href="#">SignUp</a></li>
                    </ul>
                </div>
            </div>
            <div class="logos">
                <img src="{% static 'images/Logo1.png' %}" alt="BetKing">
                <img src="{% static 'images/logo2.png' %}" alt="Fifa">
                <img src="{% static 'images/Logo3.png' %}" alt="BetKing">
                <img src="{% static 'images/Logo4.png' %}" alt="BetKing">
            </div>
            <div class="socialclass">
                <i class="fa-brands fa-facebook"></i>
                <i class="fa-brands fa-square-whatsapp"></i>
                <i class="fa-brands fa-instagram"></i>
                <i class="fa-brands fa-linkedin"></i>
                <i class="fa-brands fa-square-x-twitter"></i>
            </div>
        </section>

    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
</body>
</html>

templates/dashboard/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block content %}
<style>
    .alert{
        position: fixed;
        margin-top: 7rem;
        width: 80%;
        top: 0;
        left: 0;
        right: 0;
        text-align: center;
        span{
            color: #000;
            font-size: 15px;
        }
    }
</style>


    <!-- hero section Banner -->

    <section class="banner1">
         {% if messages %}
        {% for msg in messages %}
        <div class="alert alert-{{ msg.tags }} mx-auto"  alert-dismissible fade show" role="alert">
        <span>{{ msg }}</span>
        </div>
        {% endfor %}
        {% endif %}
   

    </section>

    <!-- Join Button section -->

    <div class="button">
        <button>Join the earning team <i class="fa-solid fa-arrow-right"></i></button>
    </div>

    <!-- Free Trial section -->

    <section class="free">
        <div class="free__div">
            <i class="fa-solid fa-triangle-exclamation"></i>
            <h2>Free Trial!</h2>
            <p>Are you looking to start-up your 
                own personal business as a Betking 
                agent in Nigeria?
            </p>
            <a href="#">My Profile <i class="fa-solid fa-arrow-right"></i></a>
        </div>
        <div class="free__div">
            <i class="fa-solid fa-clipboard-question"></i>
            <h2>Free Trial!</h2>
            <p>Are you looking to start-up your 
                own personal business as a Betking 
                agent in Nigeria?
            </p>
            <a href="#">My Profile <i class="fa-solid fa-arrow-right"></i></a>
        </div>
        <div class="free__div">
            <i class="fa-solid fa-clipboard-question"></i>
            <h2>Free Trial!</h2>
            <p>Are you looking to start-up your 
                own personal business as a Betking 
                agent in Nigeria?
            </p>
            <a href="#">My Profile <i class="fa-solid fa-arrow-right"></i></a>
        </div>
    </section>
    <section class="welcome">
        <h1>Welcome to BetKing Master</h1>
        <div class="welcome__inner">
            <div class="welcome__left">
                <img src="{% static 'images/betking.png' %}" alt="betking master">
                <p>Are you looking to start-up your own personal business
                     as a Betking agent in Nigeria? You’re probably wondering 
                     where to start from. Not to worry, I got you covered. There
                      are quite a lot of businesses that Nigerians can invest into, 
                      and  to worry, I got you covered. There are quite a lot of 
                      businesses that Nigerians can invest into, and There are
                    being a Betking agent can be a very lucrative one of those 
                    sinesses.am writing about this business idea because you can 
                    do it. As long as There areThere areThere are to worry, I 
                    got you covered. There are quite a lot of businesses that Nigerians can 
                    invest into, and  to worry, I got you covered. There are 
                    </p>
            </div>
            <div class="welcome__right">
                <h2>The King is Here</h2>
                <img src="{% static 'images/youtube.png' %}" alt="">
            </div>
        </div>
    </section>

    <!-- weekly winning code section  -->

    <section class="weekly">
        <div class="weekly__left">
            <h1>Weekly Winning Code</h1>
            <ul>
                <li><a href="#">Winning code for Saturday 29/05/2021</a></li>
                <li><a href="#">Winning code for Saturday 22/05/2021</a></li>
                <li><a href="#">Winning code for Thursday</a></li>
                <li><a href="#">Winning code for Thursday Awqv3</a></li>
                <li><a href="#">Winning code for Thursday ATZWF</a></li>
                <li><a href="#">Winning code for Thursday</a></li>
                <li><a href="#">Winning code for Friday</a></li>
            </ul>
        </div>
        <div class="weekly__right">
            <img src="{% static 'images/cover.png' %}" alt="">
        </div>
    </section>

    <h1 class="benefit">Benefits of becoming an Agent through this platform</h1>

    <section class="platform">
        <img src="{% static 'images/Logo.svg' %}" alt="Logo">
        <h2>
            This platform was designed to give necessary support, 
            courage and educate our new agents with additional benefits.
        </h2>
        <ol>
            <li><a href="#">Free configuration of laptops.</a></li>
            <li><a href="#"> Dedicated software and hardware engineers available.</a></li>
            <li><a href="#">Free configuration and installation of thin client for booking.</a></li>
            <li><a href="#">Free plasma television for you, once you refer 5 new agents to registered under this platform.</a></li>
            <li><a href="#">Short duration for inspection of an outlet/shop</a></li>
            <li><a href="#">Free registration for interested agent</a></li>
        </ol>
    </section>

    <section class="unable">
        <div class="unable__header">
            <hr> <h2>UNABLE TO DECIDE?</h2> <hr>
        </div>
        <h3>Listing to stories of Other People that Used this Plat Form</h3>
    </section>

    <!-- swiper js slide animation section -->

     <!-- --- Testimonials Section --- -->
        <div class="testi_section">
            <div class="testi_container">

                <div class="testi_card">
                    <img src="{% static 'images/quotation.png' %}" class="quote">
                    <p>"What do you need to start a business? Three simple things know your product as better to me, and
                        have a burning desire to succeed."</p>
                    <div class="test_person">
                        <img src="{% static 'images/profile2.png' %}" width="50px">
                        <div class="name_desig">
                            <h4>Penticost Smith</h4>
                            <p>Full Stack Developer</p>
                        </div>
                    </div>
                </div>
                <div class="testi_card">
                    <img src="{% static 'images/quotation.png' %}" class="quote">
                    <p>"What do you need to start a business? Three simple things know your product as better to me, and
                        have a burning desire to succeed."</p>
                    <div class="test_person">
                        <img src="{% static 'images/profile1.png' %}" width="50px">
                        <div class="name_desig">
                            <h4>Favour Philip</h4>
                            <p>Product Designer</p>
                        </div>
                    </div>
                </div>
                <div class="testi_card">
                    <img src="{% static 'images/quotation.png' %}" class="quote">
                    <p>"What do you need to start a business? Three simple things know your product as better to me, and
                        have a burning desire to succeed."</p>
                    <div class="test_person">
                        <img src="{% static 'images/profile4.png' %}" width="50px">
                        <div class="name_desig">
                            <h4>Dreamer </h4>
                            <p>Software Developer</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>


{% endblock %}